state_history: 4
buffer_size: 100
training_steps: 5000
target_update_interval: 400
t_start_training: 10
gamma: 0.95
epsilon: 0.1
epsilon_min: 0.01
epsilon_decay: 5000
batch_size: 4
learning_rate: 0.0015